version: '3'
services:
    redis:
      image: redis:alpine
      command: redis-server --appendonly yes
      restart: always
      networks:
        - internal
      volumes:
        - ./db:/data
    bot:
      build:
        context : .
      restart: always
      depends_on:
        - redis
      networks:
        - internal
      env_file:
        - bot.env
networks:
    internal:
  