version: '3'

services:
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    restart: always
    networks:
      - internal
    volumes:
      - ./db:/data

  bot:
    build: '.'
    restart: always
    depends_on:
      - redis
    networks:
      - internal
    env_file:
      - .env
    command:
      [
        "sh",
        "-c",
        "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 heleus.py --uvloop"
      ]
    ports:
      - 5678:5678

networks:
  internal:
