name: Build & Push Docker image
on: [ push ]
jobs:
  push_to_registries:
    name: Build & push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        id: prepare
        run: |
            IMAGE_NAME=heleus

            DOCKER_USER=`echo ${{ github.repository }} | cut -d "/" -f 1 | tr '[:upper:]' '[:lower:]'`
            DOCKER_REPO=`echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]'`
            DOCKER_IMAGE=ghcr.io/DOCKER_USER/$IMAGE_NAME
            DOCKER_HUB_IMAGE=DOCKER_USER/$IMAGE_NAME

            VERSION=`git rev-parse --short HEAD`
            if [[ $GITHUB_REF == refs/tags/* ]]; then
              VERSION=${GITHUB_REF#refs/tags/v}
            fi

            echo ::set-output name=docker_user::${DOCKER_USER}
            echo ::set-output name=docker_image::${DOCKER_IMAGE}
            echo ::set-output name=docker_hub_image::${IMAGE_NAME}
            echo ::set-output name=version::${VERSION}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_SECRET }}
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ steps.prepare.outputs.docker_user }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push to Registries
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ${{ steps.prepare.outputs.docker_image }}:${{ steps.prepare.outputs.version }}
            ${{ steps.prepare.outputs.docker_hub_image }}:${{ steps.prepare.outputs.version }}
